[package]
name = "hedera-protobufs-rust"
version = "0.1.0"
authors = ["davidlindner"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = { version = "0.4.3", features = ["prost"] }
tokio = "1.8.0"
prost = "0.7.0"
bytes = "1.0.1"
serde = { version = "1.0.126", features = ["derive"] }

[build-dependencies]
tonic-build = "0.4.2"
anyhow = "1.0.41"
